app.controller('aula12Controller', function($scope) {
    $scope.mostrar = true;

    $scope.variavelHTML = "<h1>Seja bem vindo ao nosso site</h1>";

    $scope.minhaClasse = "";

    $scope.variavelCloak = "VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. VARIAVEL CLOAK. "

    $scope.foto = "foto1.png";
});